# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nav_bar',
        ),
    ]
