# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_userprofile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='img',
        ),
    ]
