# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_auto_20171007_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
