# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0011_userprofile_follow_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, max_length=42, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('belong_to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.Article')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follow_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
