# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_auto_20171020_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
