# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0014_comment_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
