# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_todo_list', '0002_course_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
